/**
 * Build stat/SP digit glyph templates from the golden stats screenshot(s).
 *
 * The HP-text glyph templates (italic, sheared font from battle plates) do
 * not match the stats-screen font: even after isolating a digit from its
 * neighbor (see statDigits.ts's per-glyph mask isolation), match costs stay
 * at 0.13-0.23 against a 0.1 ceiling, and several best-matches are outright
 * wrong ('7' beats '2', '1' beats '6'). This builder captures the stats
 * screen's own upright digit font instead.
 *
 * Like the HP builder (build-hp-glyph-templates.ts), this reads BOTH pixel
 * sources — pngjs-decoded training/player-screens AND browser-decoded
 * training/player-fixtures — because the two decoders differ on ~40% of
 * bytes and templates built from one systematically mismatch glyphs masked
 * from the other. Regenerate the browser twins with:
 *   python3 scripts/capture-player-browser-fixtures.py
 *
 * Usage: npx tsx scripts/build-stat-glyph-templates.ts
 * (reads training/player-golden.json; labels apply to both source dirs)
 */
import * as fs from 'fs';
import * as path from 'path';
import { detectPlayerPanels } from '../src/features/scan/playerPanels';
import { whiteMask, filterSpecks, normalizeGlyph, MASK_THRESHOLDS, type BinMask, type GlyphTemplate } from '../src/features/scan/hpText';
import type { RgbaImage, TileBox } from '../src/features/scan/types';
import { readPng as loadPng, mergeTemplates, pruneConflicts } from './build-hp-glyph-templates';

const GOLDEN_DIR = 'training/player-screens';
const FIXTURES_DIR = 'training/player-fixtures';
const TS_PATH = path.resolve('src/features/scan/statGlyphTemplates.ts');

// Mirrors statDigits.ts's segmentDigitGlyphs: plain column-projection, no
// hpText cleanMask left-edge-component strip (that removes the HP plate's
// white frame remnant, which does not exist in these crops — but the strip
// would also delete legitimate digits that touch STATS_FRAC's column-1 edge).
function segmentDigitGlyphs(mask: BinMask): TileBox[] {
  const colHas = new Array<boolean>(mask.w).fill(false);
  for (let x = 0; x < mask.w; x++) {
    for (let y = 0; y < mask.h; y++) {
      if (mask.bits[y * mask.w + x]) { colHas[x] = true; break; }
    }
  }
  const boxes: TileBox[] = [];
  let start = -1;
  for (let x = 0; x <= mask.w; x++) {
    const has = x < mask.w && colHas[x];
    if (has && start < 0) start = x;
    if (!has && start >= 0) {
      let y0 = mask.h, y1 = -1;
      for (let y = 0; y < mask.h; y++) {
        for (let gx = start; gx < x; gx++) {
          if (mask.bits[y * mask.w + gx]) { y0 = Math.min(y0, y); y1 = Math.max(y1, y); break; }
        }
      }
      boxes.push({ x: start, y: y0, w: x - start, h: y1 - y0 + 1 });
      start = -1;
    }
  }
  return boxes;
}

// Zero out mask columns outside the glyph's own box before normalizing, so
// normalizeGlyph's padding (added when box.h > box.w, as digits are taller
// than wide) samples blank space instead of a tightly-packed neighbor glyph.
function isolateColumns(mask: BinMask, box: TileBox): BinMask {
  const bits = new Uint8Array(mask.bits.length);
  for (let y = 0; y < mask.h; y++) {
    for (let x = box.x; x < box.x + box.w; x++) bits[y * mask.w + x] = mask.bits[y * mask.w + x];
  }
  return { bits, w: mask.w, h: mask.h };
}

function templatesFromCell(img: RgbaImage, box: TileBox, expectedText: string, thresholdFactor = 0.8): GlyphTemplate[] {
  const mask = whiteMask(img, box, thresholdFactor);
  // Background sheen near some panels' edges catches whiteMask's threshold and
  // segments as an extra short blob. Every digit in a stat/SP cell renders at
  // the SAME height (unlike HP text's two-tier current/max sizes), so — unlike
  // filterSpecks's generous 0.3 ratio — a tight per-cell height filter safely
  // drops it without risking a real digit (readIntegerIn applies the same
  // filter, so builder and reader agree on what counts as a glyph).
  const rawBoxes = filterSpecks(segmentDigitGlyphs(mask), mask.h);
  const maxH = Math.max(...rawBoxes.map((b) => b.h));
  const boxes = rawBoxes.filter((b) => b.h >= maxH * 0.8).sort((a, b) => a.x - b.x);
  const chars = [...expectedText];
  if (boxes.length !== chars.length) {
    throw new Error(`expected ${chars.length} glyphs ("${expectedText}") but segmented ${boxes.length}`);
  }
  return boxes.map((b, i) => ({
    char: chars[i],
    bits: Array.from(normalizeGlyph(isolateColumns(mask, b), b)).join(''),
    hFrac: Number((b.h / mask.h).toFixed(2)),
  }));
}

function writeTemplateFile(templates: GlyphTemplate[]): void {
  fs.writeFileSync(
    TS_PATH,
    `// src/features/scan/statGlyphTemplates.ts
// GENERATED by scripts/build-stat-glyph-templates.ts. Do not edit by hand.
export const STAT_GLYPH_TEMPLATES: Array<{ char: string; bits: string; hFrac: number }> = ${JSON.stringify(templates)};
`,
  );
}

function main(): void {
  const golden = JSON.parse(fs.readFileSync('training/player-golden.json', 'utf8'));
  const sources = [GOLDEN_DIR, FIXTURES_DIR].filter((d) => fs.existsSync(d));
  let templates: GlyphTemplate[] = [];
  let built = 0;
  let skipped = 0;
  for (const dir of sources) {
    for (const [key, pair] of Object.entries<any>(golden)) {
      if (key.startsWith('_') || !pair.statsImage) continue;
      const file = `${dir}/${pair.statsImage}`;
      if (!fs.existsSync(file)) continue;
      const img = loadPng(file);
      const det = detectPlayerPanels(img);
      if (!det || det.kind !== 'stats') { console.log(`  skip ${dir}/${key}: no stats panels detected`); continue; }
      det.panels.forEach((panel, slot) => {
        const mon = pair.team[slot];
        panel.statCells!.forEach((cell, i) => {
          for (const [box, expected] of [[cell.stat, mon.stats[i]], [cell.sp, mon.sp[i]]] as const) {
            // Sweep every mask threshold the reader tries: glyph stroke weight
            // changes with the threshold, and templates from one weight do not
            // match masks produced at another (mirrors the HP builder).
            let ok = false;
            for (const thresholdFactor of MASK_THRESHOLDS) {
              try {
                templates = mergeTemplates(templates, templatesFromCell(img, box, String(expected), thresholdFactor));
                ok = true;
              } catch {
                // a threshold variant failing is fine as long as one succeeds
              }
            }
            if (ok) built++;
            else {
              skipped++;
              console.log(`  skip ${path.basename(dir)}/${key} slot${slot} cell${i} "${expected}": no threshold variant segmented`);
            }
          }
        });
      });
    }
  }
  const pruned = pruneConflicts(templates);
  writeTemplateFile(pruned);
  const chars = [...new Set(pruned.map((t) => t.char))].sort().join('');
  console.log(`Built from ${built} cell(s) across ${sources.length} source(s), skipped ${skipped}.`);
  console.log(`${pruned.length} templates (${templates.length - pruned.length} conflicted pruned) covering: ${chars}`);
}

main();
