/**
 * Build HP glyph templates from a battle screenshot with known HP text.
 *
 * Usage:
 *   npx tsx scripts/build-hp-glyph-templates.ts <screenshot.png> <side> <text-per-panel...>
 *   npx tsx scripts/build-hp-glyph-templates.ts training/screenshots/X.png opponent 100% 100%
 *   npx tsx scripts/build-hp-glyph-templates.ts training/screenshots/X.png player 157/157 177/177
 */
import { PNG } from 'pngjs';
import * as fs from 'fs';
import * as path from 'path';
import { detectBattlePanels, type BattleSide } from '../src/features/scan/battleDetection';
import {
  clusterGlyphBoxes,
  hpTextRegion,
  normalizeGlyph,
  segmentGlyphs,
  whiteMask,
  type GlyphTemplate,
} from '../src/features/scan/hpText';
import type { RgbaImage, TileBox } from '../src/features/scan/types';

const JSON_PATH = path.resolve('training/hp-glyph-templates.json');
const TS_PATH = path.resolve('src/features/scan/hpGlyphTemplates.ts');

export function readPng(file: string): RgbaImage {
  const png = PNG.sync.read(fs.readFileSync(file));
  return { data: new Uint8ClampedArray(png.data), width: png.width, height: png.height };
}

export function glyphTemplatesFromPanel(img: RgbaImage, panel: TileBox, expectedText: string): GlyphTemplate[] {
  const mask = whiteMask(img, hpTextRegion(panel, img));
  const clusters = clusterGlyphBoxes(segmentGlyphs(mask))
    .sort((a, b) => b.length - a.length || totalWidth(b) - totalWidth(a));
  const chars = [...expectedText];
  const cluster = clusters.find((c) => c.length === chars.length);
  if (!cluster) {
    throw new Error(
      `Expected ${chars.length} glyphs ("${expectedText}") but clusters have [${clusters.map((c) => c.length).join(', ')}]`,
    );
  }

  return cluster.map((box, i) => ({
    char: chars[i],
    bits: Array.from(normalizeGlyph(mask, box)).join(''),
  }));
}

export function mergeTemplates(existing: GlyphTemplate[], additions: GlyphTemplate[]): GlyphTemplate[] {
  const merged = [...existing];
  for (const t of additions) {
    if (!merged.some((m) => m.char === t.char && m.bits === t.bits)) merged.push(t);
  }
  return merged;
}

export function writeTemplateFiles(templates: GlyphTemplate[], jsonPath = JSON_PATH, tsPath = TS_PATH): void {
  fs.mkdirSync(path.dirname(jsonPath), { recursive: true });
  fs.mkdirSync(path.dirname(tsPath), { recursive: true });
  fs.writeFileSync(jsonPath, `${JSON.stringify(templates, null, 1)}\n`);
  fs.writeFileSync(
    tsPath,
    `// src/features/scan/hpGlyphTemplates.ts
// GENERATED by scripts/build-hp-glyph-templates.ts. Do not edit by hand.
export const HP_GLYPH_TEMPLATES: Array<{ char: string; bits: string }> = ${JSON.stringify(templates)};
`,
  );
}

export function buildTemplatesFromScreenshot(file: string, side: BattleSide, expected: string[]): GlyphTemplate[] {
  const img = readPng(file);
  const panels = detectBattlePanels(img, side);
  if (panels.length !== expected.length) {
    throw new Error(`Detected ${panels.length} ${side} panel(s) but got ${expected.length} expected string(s).`);
  }
  return panels.flatMap((panel, i) => glyphTemplatesFromPanel(img, panel, expected[i]));
}

function totalWidth(boxes: TileBox[]): number {
  return boxes.reduce((sum, b) => sum + b.w, 0);
}

function readExistingTemplates(jsonPath = JSON_PATH): GlyphTemplate[] {
  return fs.existsSync(jsonPath) ? JSON.parse(fs.readFileSync(jsonPath, 'utf8')) : [];
}

function main(argv: string[]): void {
  const [file, side, ...expected] = argv;
  if (!file || (side !== 'opponent' && side !== 'player') || expected.length === 0) {
    throw new Error('Usage: build-hp-glyph-templates.ts <screenshot.png> <opponent|player> <text-per-panel...>');
  }

  const existing = readExistingTemplates();
  const additions = buildTemplatesFromScreenshot(file, side, expected);
  const merged = mergeTemplates(existing, additions);
  writeTemplateFiles(merged);

  const added = merged.length - existing.length;
  const chars = [...new Set(merged.map((t) => t.char))].sort().join('');
  console.log(`Added ${added} template(s); ${merged.length} total covering: ${chars}`);
  console.log('Coverage needed: 0123456789/% - run again on more screenshots for missing chars.');
}

if (process.argv[1] && process.argv[1].endsWith('build-hp-glyph-templates.ts')) {
  try {
    main(process.argv.slice(2));
  } catch (error) {
    console.error((error as Error).message);
    process.exit(1);
  }
}
